### ISSUE TITLE
Provide project description for Pypi

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-python#216] opened 2018-04-29 21:26 UTC
https://pypi.org/project/iopipe/

The Pypi page says that the author has not provided a description.

![screen shot 2018-04-29 at 2 25 06 pm](https://user-images.githubusercontent.com/168944/39411155-382c596c-4bb9-11e8-96f7-f05c2ebd80a6.png)

**Comment by kolanos** [comment] 2018-05-03 19:42
Duplicate of #202

**Closed** 2018-05-03 19:42 UTC
